### defer和async

1. defer和async都是用于在不阻塞页面文档解析的前提下，控制脚本的下载和执行。
2. defer用于开启一个新的线程下载脚本文件，并使脚本在文档解析完成后、DOMContentloader和load事件之前执行。
3. async用于异步下载脚本文件，会在脚本下载完成之后立即执行。

### 处理异步的几种方法

1. 回调函数

   回调是一个函数作为一个参数传递到另一个函数里，在那个函数执行完成后再执行。
   回调函数是异步编程最基本的方法，优点是简单，容易理解和部署，缺点是不利于代码的阅读和维护，各个部分之间高度耦合，流程会很乱，每个任务只能指定一个回调函数

2. 事件监听

   采用事件驱动模式，任务执行时不取决于代码顺序，取决于事件是否触发。
   具体方法有：
   （1）onclick方法
   （2）attachEvent和addEvenListener方法。

3. 发布和订阅

   我们假定，存在一个"信号中心"，某个任务执行完成，就向信号中心"发布"（publish）一个信号，其他任务可以向信号中心"订阅"（subscribe）这个信号，从而知道什么时候自己可以开始执行。

4. promise对象

5. async和await

### ajax可以取消吗？

- 可以

  ```js
  var native = new XMLHttpRequest();
  native.open("GET","https://api.github.com/");
  native.send();
  native.onreadystatechange=function(){
      if(native.readyState==4&&native.status==200){
          console.log(native.response);           
      }else{
          console.log(native.status);
      }
  }
  native.abort();
  ```

### axios请求可以取消吗？

- **axios**：如果我们经常使用vue等框架的话，就会使用axios发送ajax请求。在axios中取消ajax请求不同于上面两种形式，在axios中是通过**axios.CancelToken.source()**方法取消请求。

  ```js
  var CancelToken = axios.CancelToken;
  var source = CancelToken.source();
  axios({
      method:"GET",
      url:"https://api.github.com/",
      cancelToken:source.token
      //cancelToken的值起标识作用，标识由source控制的、将要被取消的ajax操作
  }).then((res) => {
      console.log(res.data);
  }).catch((err) => {
      console.log(err);
  });
  source.cancel('Operation canceled by the user.');
  ```

### Promise请求可以取消吗？

- 可以

  ```js
  //promise取消或者中断的两种方法：
  //1、利用这一特性，当新对象保持“pending”状态时，原Promise链将会中止执行。
  Promise.resolve().then(() => {
      console.log('ok1')
      return new Promise(()=>{})  // 返回“pending”状态的Promise对象
  }).then(() => {
      // 后续的函数不会被调用
      console.log('ok2')
  }).catch(err => {
      console.log('err->', err)
  })
  //2、Promise.race竞速方法
  let p1 = new Promise((resolve, reject) => {
      resolve('ok1')
  })
  let p2 = new Promise((resolve, reject) => {
      setTimeout(() => {resolve('ok2')}, 10)
  })
  Promise.race([p2, p1]).then((result) => {
      console.log(result) //ok1
  }).catch((error) => {
      console.log(error)
  })
  ```

  

